create table MASTERDATA
(
  id          number generated by default on null as identity,
  status      varchar2(100) not null,
  create_user varchar2(100) not null,
  create_date date default SYSDATE not null,
  update_user varchar2(100),
  update_date date
)
;