-- Create table
create table APP_WORKFLOW_STEP
(
  id              number generated by default on null as identity,
  action          varchar2(100) not null,
  request         varchar2(100) not null,
  status          varchar2(100) not null,
  next_page       number(*,0) not null,
  prev_step_id    number(*,0),
  app_workflow_id number(*,0) not null,
  create_user     varchar2(100) not null,
  create_date     date default SYSDATE not null,
  update_user     varchar2(100),
  update_date     date
)
;