-- Create table
create table APP_WORKFLOW_DICTIONARY
(
  id              number generated by default on null as identity,
  dictionary_name varchar2(100) not null,
  entry_text      varchar2(100) not null,
  create_user     varchar2(100) not null,
  create_date     date default SYSDATE not null,
  update_user     varchar2(100),
  update_date     date
)
;